# Generated by Django 3.0.3 on 2020-06-04 21:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(max_length=48, null=True, unique=True, verbose_name='电话')),
                ('email', models.EmailField(max_length=48, null=True, unique=True, verbose_name='邮箱')),
                ('password', models.CharField(max_length=48, verbose_name='密码')),
                ('name', models.CharField(max_length=48, verbose_name='姓名')),
                ('gender', models.CharField(blank=True, choices=[('0', '未知'), ('1', '男'), ('2', '女')], default='0', max_length=32, verbose_name='性别')),
                ('identity', models.CharField(blank=True, choices=[('user', '普通用户'), ('vip', '会员'), ('admin', '管理员')], default='user', max_length=32, verbose_name='身份')),
                ('intro', models.CharField(blank=True, default='', max_length=256, verbose_name='简介')),
                ('job', models.CharField(blank=True, default='', max_length=256, verbose_name='职业')),
                ('school', models.CharField(blank=True, default='', max_length=256, verbose_name='学校')),
                ('company', models.CharField(blank=True, default='', max_length=256, verbose_name='公司')),
                ('session_key', models.CharField(blank=True, default='', max_length=256, verbose_name='session键')),
                ('login_date', models.DateField(auto_now=True, verbose_name='最近登录时间')),
                ('view_day', models.IntegerField(blank=True, default=0, verbose_name='最近一天浏览次数')),
                ('star_day', models.IntegerField(blank=True, default=0, verbose_name='最近一天收藏次数')),
                ('like_day', models.IntegerField(blank=True, default=0, verbose_name='最近一天被点赞次数')),
                ('point_day', models.IntegerField(blank=True, default=0, verbose_name='最近一天获得积分数')),
                ('comment_day', models.IntegerField(blank=True, default=0, verbose_name='最近一天被评论次数')),
                ('view_count', models.IntegerField(blank=True, default=0, verbose_name='总评论次数')),
                ('star_count', models.IntegerField(blank=True, default=0, verbose_name='总收藏次数')),
                ('like_count', models.IntegerField(blank=True, default=0, verbose_name='总被点赞次数')),
                ('comment_count', models.IntegerField(blank=True, default=0, verbose_name='总被评论次数')),
                ('wrong_count', models.IntegerField(blank=True, default=0, verbose_name='最近一天密码错误次数')),
                ('vip_date', models.DateField(blank=True, default=datetime.date(1900, 1, 1), verbose_name='会员到期时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('article_id', models.IntegerField(default=-1, verbose_name='置顶文章id')),
                ('blocked', models.BooleanField(blank=True, default=False, verbose_name='被封禁')),
                ('birthday', models.DateField(blank=True, default=datetime.date(1900, 1, 1), verbose_name='生日')),
                ('file_size', models.IntegerField(blank=True, default=0, verbose_name='上传资源总大小')),
                ('point', models.IntegerField(blank=True, default=0, verbose_name='积分')),
                ('profile_photo', models.FileField(blank=True, default='', max_length=256, upload_to='', verbose_name='头像路径')),
                ('followers', models.ManyToManyField(blank=True, related_name='_user_followers_+', to='user.User')),
                ('followings', models.ManyToManyField(blank=True, related_name='_user_followings_+', to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed', to='user.User')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField(default=0, verbose_name='积分变动')),
                ('reason', models.CharField(max_length=256, verbose_name='理由')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
