# Generated by Django 3.0.3 on 2020-06-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200607_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login_date',
            field=models.DateField(auto_now_add=True, verbose_name='最近登录时间'),
        ),
    ]
