# Generated by Django 3.0.3 on 2020-06-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='description',
            new_name='content',
        ),
        migrations.AddField(
            model_name='resource',
            name='recycled',
            field=models.BooleanField(blank=True, default=False, verbose_name='在回收站里'),
        ),
    ]
