# Generated by Django 3.0.3 on 2020-06-07 19:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0002_auto_20200607_1900'),
        ('article', '0001_initial'),
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='complain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complain_message', to='mainpage.Complain'),
        ),
        migrations.AddField(
            model_name='message',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='article_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_comment_message', to='article.ArticleComment'),
        ),
        migrations.AlterField(
            model_name='message',
            name='resource_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_comment_message', to='resource.ResourceComment'),
        ),
    ]
