# Generated by Django 3.0.3 on 2020-06-08 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0002_auto_20200607_1900'),
        ('mainpage', '0002_auto_20200607_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='resource',
            field=models.ManyToManyField(related_name='tagged_resource', to='resource.Resource'),
        ),
    ]
